### ISSUE TITLE
Support for multiple domains

### ISSUE THREAD

**Issue by marvinroger** [sseemayer/dokku-letsencrypt#4]
An app might have multiple domains. dokku-letsencrypt should be able to obtain a certificate for all domains.

BTW, thanks for this plugin! This will definitely help a lot of people.

**Comment by sseemayer** [comment]
I've added an experimental multiple domain support but was only test this on several subdomains of the same domain until I hit a rate limit by letsencrypt. Could you please give feedback?

**Comment by marvinroger** [comment]
That was fast! Of course I will, probably tomorrow. Will report back.

**Comment by marvinroger** [comment]
It works, thanks!

**Comment by figalex** [comment]
I'm having a problem trying to do this. I want to have 4 different subdomains with ssl certificate but at one point all of my subdomains start using the same certificate. For example, if I have apps.domain.com and accounts.domain.com, at one point when I open apps.domains.com on my browser it tells me that the certificate is invalid because that certificate is for accounts.domain.com. 

What could I be doing wrong?
