### ISSUE TITLE
Certificate limit easily hit

### ISSUE THREAD

**Issue by oelmekki** [sseemayer/dokku-letsencrypt#8]
Hi there,

Thanks for dokku-letsencrypt, it's almost magical after being used to 
non letsencrypt ssl configuration :)

One problem with it is that the rate limit for letsencrypt is very 
easily hit:

```
An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: <domain>
Please see the logfiles in /var/log/letsencrypt for more details.
```

The problem is that it will try to issue a certificate for every single
domain of the app, included the default `<app>.<dokku_domain>` one (so
making sure to use a domain per app wouldn't help).

Do you think it would be possible to either omit the default domain, or 
maybe to specify which domains should have a ssl certificate?

**Comment by sseemayer** [comment]
I'm glad you're enjoying the plugin - and yeah, making certificate issuance this fun makes it very easy to run into the rate limit :-)

The way I understand the [let's encrypt rate limits](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769), there are two important limits here: the number of *common names/certificate* (100 at the time of writing) and the number of *certificates/domain/week* (5 per rolling window of 7 days). At the moment, one certificate is requested for each app, using the result of 'dokku urls myapp' to resolve common names. 

The way I see it, the names / certificate limit is not a problem since we typically can reach an app under fewer than 100 names and the limiting factor will be the 5 certificates (in our case, 5 apps) per week. 

I'm afraid that the solution you suggest might not be compatible with the default SSL support in dokku since it's not possible to install an SSL certificate for only some of the urls under which an app can be reached. The URLs deselected would still attempt to upgrade their connections to SSL and then fail with an invalid cerificate. 

One possibility would be to make dokku-letsencrypt enumerate all let's encrypt secured apps installed at any moment and bundle all their urls into one certificate request. That would probably make things more complicated and I'd have to think about all consequences of this for a bit more. I'll come back to this after the new year!

**Comment by oelmekki** [comment]
@sseemayer thanks for quick reply ;)

I've just found a workaround, mentioning it in README could be good 
enough: default domains can actually be removed, so maybe we could tell 
next users that if they wish to encrypt many apps, they would have 
better to use `dokku domains:add` to add a specific domain and 
`dokku domains:remove` to remove default domain.

Btw, a mean to use the `revoke` command would be great to, especially 
when one went to boldly add ssl everywhere like I did :P 

Have nice holidays!

**Comment by sseemayer** [comment]
That's a helpful workaround, would you mind creating a PR for the readme? A revoke command is a good idea although I'm not sure if it's necessary to revoke if there is no chance that private keys were compromised

**Comment by oelmekki** [comment]
Done :)

I was thinking to use `revoke` to be able to fix the rate limit 
situation without having to wait for a week, but maybe it could be 
considered an edge case.

**Comment by sseemayer** [comment]
The revocation of a certificate will not affect the rate limit, only waiting 7 days will :-( 

Again, thanks for the PR!

**Comment by sseemayer** [comment]
Adding revocation will be discussed in #9.

**Comment by oelmekki** [comment]
You're welcome!


> The revocation of a certificate will not affect the rate limit, only waiting 7 days will :-(

Oh snap... Well, will have to be patient :)

**Comment by Mailerm** [comment]
i hava 6 certificates for my domain, have to wait...
